---
title: "test"
output: html_document
date: "2022-11-06"
---

```{r}
#test3
df = read.csv("amazon_review_polarity_csv/train.csv", header = FALSE)
```

```{r}
reviews_text<-readLines("amazon_review_polarity_csv/train.csv", n = 1000)
reviews_text<-data.frame(reviews_text)
```

```{r}
library(tidyr) 
reviews_text<-separate(data = reviews_text, col = reviews_text, into = c("Sentiment", "SentimentText"), sep = 4)
```

```{r}
# Retaining only alphanumeric values in the sentiment column
reviews_text$Sentiment<-gsub("[^[:alnum:] ]","",reviews_text$Sentiment) 
# Retaining only alphanumeric values in the sentiment text
reviews_text$SentimentText<-gsub("[^[:alnum:] ]"," ",reviews_text$SentimentText) 
# Replacing multiple spaces in the text with single space
reviews_text$SentimentText<-gsub("(?<=[\\s])\\s*|^\\s+|\\s+$", "", reviews_text$SentimentText, perl=TRUE) 
# Writing the output to a file that can be consumed in other projects
write.table(reviews_text,file = "Sentiment Analysis Dataset.csv",row.names = F,col.names = T,sep=',')
```

```{r}
# reading the first 1000 reviews from the dataset
reviews_text<-readLines('amazon_review_polarity_csv/train.csv', n = 1000)
# basic EDA to confirm that the data is read correctly 
print(class(reviews_text)) 
print(length(reviews_text)) 
print(head(reviews_text,2)) 
# replacing the positive sentiment value 2 with __label__2
reviews_text<-gsub("\\\"2\\\",","__label__2 ",reviews_text) 
# replacing the negative sentiment value 1 with __label__1
reviews_text<-gsub("\\\"1\\\",","__label__1 ",reviews_text) 
# removing the unnecessary \" characters 
reviews_text<-gsub("\\\""," ",reviews_text) 
# replacing multiple spaces in the text with single space
reviews_text<-gsub("(?<=[\\s])\\s*|^\\s+|\\s+$", "", reviews_text, perl=TRUE) 
# Basic EDA post the required processing to confirm input is as desired 
print("EDA POST PROCESSING") 
print(class(reviews_text)) 
print(length(reviews_text)) 
print(head(reviews_text,2)) 
# writing the revamped file to the directory so we could use it with 
# fastText sentiment analyzer project
fileConn<-file("Sentiment Analysis Dataset_ft.txt") 
writeLines(reviews_text, fileConn) 
close(fileConn)
```

